# Generated by Django 6.0 on 2026-04-15 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('AD', 'Adamaoua'), ('CE', 'Centre'), ('ES', 'Est'), ('EN', 'Extrême-Nord'), ('LI', 'Littoral'), ('NO', 'Nord'), ('NW', 'Nord-Ouest'), ('OU', 'Ouest'), ('SU', 'Sud'), ('SW', 'Sud-Ouest')], max_length=2)),
            ],
            options={
                'verbose_name': 'District de Santé',
                'verbose_name_plural': 'Districts de Santé',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(choices=[('CHOLERA', 'Choléra'), ('ROUGEOLE', 'Rougeole'), ('PALU_GRAVE', 'Paludisme Grave'), ('FIEVRE_JAUNE', 'Fièvre Jaune'), ('MENINGITE', 'Méningite'), ('POLIO', 'Poliomyélite')], max_length=50)),
                ('nombre_cas', models.PositiveIntegerField(verbose_name='Nombre de cas')),
                ('nombre_deces', models.PositiveIntegerField(default=0, verbose_name='Nombre de décès')),
                ('date_evenement', models.DateField(verbose_name="Date d'apparition")),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('agent_sante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.districtsante')),
            ],
            options={
                'verbose_name': 'Signalement de cas',
                'verbose_name_plural': 'Signalements de cas',
            },
        ),
    ]
