# Generated by Django 6.0 on 2026-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-date_declaration']},
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='agent_sante',
        ),
        migrations.AddField(
            model_name='signalement',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtsante',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='districtsante',
            name='region',
            field=models.CharField(choices=[('AD', 'Adamaoua'), ('CE', 'Centre'), ('EN', 'Extrême-Nord'), ('ES', 'Est'), ('LT', 'Littoral'), ('NO', 'Nord'), ('NW', 'Nord-Ouest'), ('OU', 'Ouest'), ('SU', 'Sud'), ('SW', 'Sud-Ouest')], max_length=5),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='date_evenement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='maladie',
            field=models.CharField(choices=[('CHOLERA', 'Choléra'), ('MALARIA', 'Malaria'), ('ROUGEOLE', 'Rougeole'), ('FIEVRE_JAUNE', 'Fièvre Jaune'), ('COVID19', 'COVID-19'), ('POLIO', 'Poliomyélite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='nombre_cas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='nombre_deces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
